apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-pvc
  namespace: flyeasy
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: flyeasy-ebs-gp3
  resources:
    requests:
      storage: 5Gi
