apiVersion: apps/v1
kind: Deployment
metadata:
  name: flyeasy-backend
  namespace: flyeasy
  labels:
    app: flyeasy-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flyeasy-backend
  template:
    metadata:
      labels:
        app: flyeasy-backend
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: flyeasy-backend
          image: 847776737366.dkr.ecr.us-east-2.amazonaws.com/flyeasy-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "5000"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: flyeasy-backend-secrets
                  key: JWT_SECRET
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: flyeasy-backend-secrets
                  key: MONGO_URI
