apiVersion: v1
kind: Service
metadata:
  name: flyeasy-backend
  namespace: flyeasy
spec:
  selector:
    app: flyeasy-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
